// This file will be auto-generated by Supabase CLI after migrations are run
// Run: npx supabase gen types typescript --project-id your-project-ref > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'job_seeker' | 'mentor'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'job_seeker' | 'mentor'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'job_seeker' | 'mentor'
          created_at?: string
          updated_at?: string
        }
      }
      career_canvas: {
        Row: {
          id: string
          user_id: string
          section_1_helpers: string | null
          section_2_activities: string | null
          section_3_value: string | null
          section_4_interactions: string | null
          section_5_convince: string | null
          section_6_skills: string | null
          section_7_motivation: string | null
          section_8_sacrifices: string | null
          section_9_outcomes: string | null
          completion_percentage: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          section_1_helpers?: string | null
          section_2_activities?: string | null
          section_3_value?: string | null
          section_4_interactions?: string | null
          section_5_convince?: string | null
          section_6_skills?: string | null
          section_7_motivation?: string | null
          section_8_sacrifices?: string | null
          section_9_outcomes?: string | null
          completion_percentage?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          section_1_helpers?: string | null
          section_2_activities?: string | null
          section_3_value?: string | null
          section_4_interactions?: string | null
          section_5_convince?: string | null
          section_6_skills?: string | null
          section_7_motivation?: string | null
          section_8_sacrifices?: string | null
          section_9_outcomes?: string | null
          completion_percentage?: number
          created_at?: string
          updated_at?: string
        }
      }
      ninety_day_plans: {
        Row: {
          id: string
          user_id: string
          title: string
          start_date: string
          end_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          start_date: string
          end_date: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          start_date?: string
          end_date?: string
          created_at?: string
          updated_at?: string
        }
      }
      weekly_milestones: {
        Row: {
          id: string
          plan_id: string
          week_number: number
          goal: string
          notes: string | null
          status: 'not_started' | 'in_progress' | 'completed'
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          plan_id: string
          week_number: number
          goal?: string
          notes?: string | null
          status?: 'not_started' | 'in_progress' | 'completed'
          order_index: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          plan_id?: string
          week_number?: number
          goal?: string
          notes?: string | null
          status?: 'not_started' | 'in_progress' | 'completed'
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      companies: {
        Row: {
          id: string
          user_id: string
          name: string
          website_url: string | null
          status: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes: string | null
          date_added: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          website_url?: string | null
          status?: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes?: string | null
          date_added?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          website_url?: string | null
          status?: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes?: string | null
          date_added?: string
          created_at?: string
          updated_at?: string
        }
      }
      resume_analyses: {
        Row: {
          id: string
          user_id: string
          file_name: string
          file_url: string
          ats_score: number
          strengths: string[]
          gaps: string[]
          recommendations: string[]
          candidate_name: string | null
          target_country: string | null
          summary: string | null
          experience_level: string | null
          skills_identified: string[] | null
          role_recommendations: string[] | null
          job_search_approach: string[] | null
          ninety_day_strategy: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          file_name: string
          file_url: string
          ats_score: number
          strengths: string[]
          gaps: string[]
          recommendations: string[]
          candidate_name?: string | null
          target_country?: string | null
          summary?: string | null
          experience_level?: string | null
          skills_identified?: string[] | null
          role_recommendations?: string[] | null
          job_search_approach?: string[] | null
          ninety_day_strategy?: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          file_name?: string
          file_url?: string
          ats_score?: number
          strengths?: string[]
          gaps?: string[]
          recommendations?: string[]
          candidate_name?: string | null
          target_country?: string | null
          summary?: string | null
          experience_level?: string | null
          skills_identified?: string[] | null
          role_recommendations?: string[] | null
          job_search_approach?: string[] | null
          ninety_day_strategy?: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date?: string
          created_at?: string
        }
      }
      ai_usage_tracking: {
        Row: {
          id: string
          user_id: string
          feature_type: 'resume_analysis' | 'plan_suggestions'
          usage_month: string
          usage_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          feature_type: 'resume_analysis' | 'plan_suggestions'
          usage_month: string
          usage_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          feature_type?: 'resume_analysis' | 'plan_suggestions'
          usage_month?: string
          usage_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      mentor_invitations: {
        Row: {
          id: string
          job_seeker_id: string
          mentor_email: string
          status: 'pending' | 'accepted' | 'rejected'
          personal_message: string | null
          invitation_token: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_seeker_id: string
          mentor_email: string
          status?: 'pending' | 'accepted' | 'rejected'
          personal_message?: string | null
          invitation_token: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_seeker_id?: string
          mentor_email?: string
          status?: 'pending' | 'accepted' | 'rejected'
          personal_message?: string | null
          invitation_token?: string
          created_at?: string
          updated_at?: string
        }
      }
      // Add other table types as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
