// This file will be auto-generated by Supabase CLI after migrations are run
// Run: npx supabase gen types typescript --project-id your-project-ref > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Career Plan Template types
export interface CareerPlanTemplate {
  id: string
  name: string
  target_role: string
  description: string
  icon: string
  color: string
  is_featured: boolean
  is_active: boolean
  weeks: TemplateWeek[]
  created_at: string
  updated_at: string
}

export interface TemplateWeek {
  week: number
  title: string
  theme: 'foundation' | 'skill_development' | 'networking' | 'job_search'
  goals: string[]
}

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'job_seeker' | 'mentor' | 'admin' | 'super_admin'
          is_admin: boolean
          // Contact Information
          phone_number: string | null
          current_location: string | null
          linkedin_url: string | null
          // Career Information
          years_of_experience: string | null
          job_title: string | null
          specialization: string | null
          areas_of_expertise: string[] | null
          // Career Goals
          target_role: string | null
          target_industry: string | null
          job_search_status: 'actively_looking' | 'passively_looking' | 'employed_not_looking' | 'open_to_opportunities' | null
          work_preference: 'remote' | 'hybrid' | 'onsite' | 'flexible' | null
          salary_expectation: string | null
          education_level: 'high_school' | 'associate' | 'bachelor' | 'master' | 'doctorate' | 'other' | null
          skills: string[] | null
          // Onboarding
          profile_completed: boolean
          onboarding_completed_at: string | null
          // Usage Limits
          resume_analysis_limit: number
          // Timezone
          timezone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'job_seeker' | 'mentor' | 'admin' | 'super_admin'
          is_admin?: boolean
          phone_number?: string | null
          current_location?: string | null
          linkedin_url?: string | null
          years_of_experience?: string | null
          job_title?: string | null
          specialization?: string | null
          areas_of_expertise?: string[] | null
          target_role?: string | null
          target_industry?: string | null
          job_search_status?: 'actively_looking' | 'passively_looking' | 'employed_not_looking' | 'open_to_opportunities' | null
          work_preference?: 'remote' | 'hybrid' | 'onsite' | 'flexible' | null
          salary_expectation?: string | null
          education_level?: 'high_school' | 'associate' | 'bachelor' | 'master' | 'doctorate' | 'other' | null
          skills?: string[] | null
          profile_completed?: boolean
          onboarding_completed_at?: string | null
          resume_analysis_limit?: number
          timezone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'job_seeker' | 'mentor' | 'admin' | 'super_admin'
          is_admin?: boolean
          phone_number?: string | null
          current_location?: string | null
          linkedin_url?: string | null
          years_of_experience?: string | null
          job_title?: string | null
          specialization?: string | null
          areas_of_expertise?: string[] | null
          target_role?: string | null
          target_industry?: string | null
          job_search_status?: 'actively_looking' | 'passively_looking' | 'employed_not_looking' | 'open_to_opportunities' | null
          work_preference?: 'remote' | 'hybrid' | 'onsite' | 'flexible' | null
          salary_expectation?: string | null
          education_level?: 'high_school' | 'associate' | 'bachelor' | 'master' | 'doctorate' | 'other' | null
          skills?: string[] | null
          profile_completed?: boolean
          onboarding_completed_at?: string | null
          resume_analysis_limit?: number
          timezone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      ai_prompts: {
        Row: {
          id: string
          name: string
          description: string | null
          model: string
          max_tokens: number
          temperature: number
          system_prompt: string
          user_prompt_template: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          description?: string | null
          model?: string
          max_tokens?: number
          temperature?: number
          system_prompt: string
          user_prompt_template: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          model?: string
          max_tokens?: number
          temperature?: number
          system_prompt?: string
          user_prompt_template?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      career_canvas: {
        Row: {
          id: string
          user_id: string
          name: string
          target_role: string | null
          current_role: string | null
          target_date: string | null
          industry: string | null
          section_1_helpers: string | null
          section_2_activities: string | null
          section_3_value: string | null
          section_4_interactions: string | null
          section_5_convince: string | null
          section_6_skills: string | null
          section_7_motivation: string | null
          section_8_sacrifices: string | null
          section_9_outcomes: string | null
          completion_percentage: number
          linked_plan_id: string | null
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name?: string
          target_role?: string | null
          current_role?: string | null
          target_date?: string | null
          industry?: string | null
          section_1_helpers?: string | null
          section_2_activities?: string | null
          section_3_value?: string | null
          section_4_interactions?: string | null
          section_5_convince?: string | null
          section_6_skills?: string | null
          section_7_motivation?: string | null
          section_8_sacrifices?: string | null
          section_9_outcomes?: string | null
          completion_percentage?: number
          linked_plan_id?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          target_role?: string | null
          current_role?: string | null
          target_date?: string | null
          industry?: string | null
          section_1_helpers?: string | null
          section_2_activities?: string | null
          section_3_value?: string | null
          section_4_interactions?: string | null
          section_5_convince?: string | null
          section_6_skills?: string | null
          section_7_motivation?: string | null
          section_8_sacrifices?: string | null
          section_9_outcomes?: string | null
          completion_percentage?: number
          linked_plan_id?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      ninety_day_plans: {
        Row: {
          id: string
          user_id: string
          title: string
          start_date: string
          end_date: string
          parent_plan_id: string | null
          sequence_number: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          start_date: string
          end_date: string
          parent_plan_id?: string | null
          sequence_number?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          start_date?: string
          end_date?: string
          parent_plan_id?: string | null
          sequence_number?: number
          created_at?: string
          updated_at?: string
        }
      }
      weekly_milestones: {
        Row: {
          id: string
          plan_id: string
          week_number: number
          goal: string
          notes: string | null
          status: 'not_started' | 'in_progress' | 'completed'
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          plan_id: string
          week_number: number
          goal?: string
          notes?: string | null
          status?: 'not_started' | 'in_progress' | 'completed'
          order_index: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          plan_id?: string
          week_number?: number
          goal?: string
          notes?: string | null
          status?: 'not_started' | 'in_progress' | 'completed'
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      companies: {
        Row: {
          id: string
          user_id: string
          name: string
          website_url: string | null
          status: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes: string | null
          date_added: string
          created_at: string
          updated_at: string
          // Contact Information
          contact_name: string | null
          contact_email: string | null
          contact_phone: string | null
          contact_linkedin: string | null
          contact_title: string | null
          // Job Details
          job_title: string | null
          job_posting_url: string | null
          salary_range: string | null
          // Company Details
          industry: string | null
          company_size: string | null
          location: string | null
          company_linkedin: string | null
          // Tracking Fields
          application_date: string | null
          last_contact_date: string | null
          next_followup_date: string | null
          referral_source: string | null
          priority: number
          is_favorite: boolean
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          website_url?: string | null
          status?: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes?: string | null
          date_added?: string
          created_at?: string
          updated_at?: string
          // Contact Information
          contact_name?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          contact_linkedin?: string | null
          contact_title?: string | null
          // Job Details
          job_title?: string | null
          job_posting_url?: string | null
          salary_range?: string | null
          // Company Details
          industry?: string | null
          company_size?: string | null
          location?: string | null
          company_linkedin?: string | null
          // Tracking Fields
          application_date?: string | null
          last_contact_date?: string | null
          next_followup_date?: string | null
          referral_source?: string | null
          priority?: number
          is_favorite?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          website_url?: string | null
          status?: 'researching' | 'applied' | 'interviewing' | 'offer' | 'rejected'
          notes?: string | null
          date_added?: string
          created_at?: string
          updated_at?: string
          // Contact Information
          contact_name?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          contact_linkedin?: string | null
          contact_title?: string | null
          // Job Details
          job_title?: string | null
          job_posting_url?: string | null
          salary_range?: string | null
          // Company Details
          industry?: string | null
          company_size?: string | null
          location?: string | null
          company_linkedin?: string | null
          // Tracking Fields
          application_date?: string | null
          last_contact_date?: string | null
          next_followup_date?: string | null
          referral_source?: string | null
          priority?: number
          is_favorite?: boolean
        }
      }
      resume_analyses: {
        Row: {
          id: string
          user_id: string
          file_name: string
          file_url: string
          ats_score: number
          strengths: string[]
          gaps: string[]
          recommendations: string[]
          candidate_name: string | null
          target_country: string | null
          summary: string | null
          experience_level: string | null
          skills_identified: string[] | null
          role_recommendations: string[] | null
          job_search_approach: string[] | null
          ninety_day_strategy: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          file_name: string
          file_url: string
          ats_score: number
          strengths: string[]
          gaps: string[]
          recommendations: string[]
          candidate_name?: string | null
          target_country?: string | null
          summary?: string | null
          experience_level?: string | null
          skills_identified?: string[] | null
          role_recommendations?: string[] | null
          job_search_approach?: string[] | null
          ninety_day_strategy?: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          file_name?: string
          file_url?: string
          ats_score?: number
          strengths?: string[]
          gaps?: string[]
          recommendations?: string[]
          candidate_name?: string | null
          target_country?: string | null
          summary?: string | null
          experience_level?: string | null
          skills_identified?: string[] | null
          role_recommendations?: string[] | null
          job_search_approach?: string[] | null
          ninety_day_strategy?: {
            overview: string
            weeks_1_4: string[]
            weeks_5_8: string[]
            weeks_9_12: string[]
          } | null
          analysis_date?: string
          created_at?: string
        }
      }
      ai_usage_tracking: {
        Row: {
          id: string
          user_id: string
          feature_type: 'resume_analysis' | 'plan_suggestions'
          usage_month: string
          usage_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          feature_type: 'resume_analysis' | 'plan_suggestions'
          usage_month: string
          usage_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          feature_type?: 'resume_analysis' | 'plan_suggestions'
          usage_month?: string
          usage_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      mentor_invitations: {
        Row: {
          id: string
          job_seeker_id: string
          mentor_email: string
          status: 'pending' | 'accepted' | 'rejected'
          personal_message: string | null
          invitation_token: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_seeker_id: string
          mentor_email: string
          status?: 'pending' | 'accepted' | 'rejected'
          personal_message?: string | null
          invitation_token: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_seeker_id?: string
          mentor_email?: string
          status?: 'pending' | 'accepted' | 'rejected'
          personal_message?: string | null
          invitation_token?: string
          created_at?: string
          updated_at?: string
        }
      }
      job_listings: {
        Row: {
          id: string
          user_id: string
          company_id: string | null
          title: string
          company_name: string
          location: string | null
          job_url: string | null
          source: 'linkedin' | 'indeed' | 'glassdoor' | 'company_site' | 'referral' | 'other' | null
          description: string | null
          salary_range: string | null
          job_type: 'full_time' | 'part_time' | 'contract' | 'internship' | 'remote' | null
          application_status: 'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected' | 'withdrawn'
          applied_date: string | null
          deadline: string | null
          notes: string | null
          is_favorite: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          company_id?: string | null
          title: string
          company_name: string
          location?: string | null
          job_url?: string | null
          source?: 'linkedin' | 'indeed' | 'glassdoor' | 'company_site' | 'referral' | 'other' | null
          description?: string | null
          salary_range?: string | null
          job_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'remote' | null
          application_status?: 'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected' | 'withdrawn'
          applied_date?: string | null
          deadline?: string | null
          notes?: string | null
          is_favorite?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          company_id?: string | null
          title?: string
          company_name?: string
          location?: string | null
          job_url?: string | null
          source?: 'linkedin' | 'indeed' | 'glassdoor' | 'company_site' | 'referral' | 'other' | null
          description?: string | null
          salary_range?: string | null
          job_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'remote' | null
          application_status?: 'saved' | 'applied' | 'interviewing' | 'offer' | 'rejected' | 'withdrawn'
          applied_date?: string | null
          deadline?: string | null
          notes?: string | null
          is_favorite?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: 'interview_reminder' | 'follow_up' | 'milestone_due' | 'plan_reminder' | 'system'
          title: string
          message: string
          link: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'interview_reminder' | 'follow_up' | 'milestone_due' | 'plan_reminder' | 'system'
          title: string
          message: string
          link?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'interview_reminder' | 'follow_up' | 'milestone_due' | 'plan_reminder' | 'system'
          title?: string
          message?: string
          link?: string | null
          is_read?: boolean
          created_at?: string
        }
      }
      notification_preferences: {
        Row: {
          id: string
          user_id: string
          email_interview_reminder: boolean
          email_follow_up_reminder: boolean
          email_milestone_reminder: boolean
          email_weekly_summary: boolean
          in_app_enabled: boolean
          reminder_days_before: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          email_interview_reminder?: boolean
          email_follow_up_reminder?: boolean
          email_milestone_reminder?: boolean
          email_weekly_summary?: boolean
          in_app_enabled?: boolean
          reminder_days_before?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          email_interview_reminder?: boolean
          email_follow_up_reminder?: boolean
          email_milestone_reminder?: boolean
          email_weekly_summary?: boolean
          in_app_enabled?: boolean
          reminder_days_before?: number
          created_at?: string
          updated_at?: string
        }
      }
      interviews: {
        Row: {
          id: string
          user_id: string
          company_id: string | null
          company_name: string
          position: string
          interview_type: 'phone_screen' | 'technical' | 'behavioral' | 'final' | 'offer' | 'other'
          scheduled_at: string | null
          status: 'scheduled' | 'completed' | 'cancelled' | 'rescheduled'
          prep_notes: string | null
          questions_asked: string[] | null
          interviewer_names: string[] | null
          feedback: string | null
          follow_up_date: string | null
          follow_up_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          company_id?: string | null
          company_name: string
          position: string
          interview_type: 'phone_screen' | 'technical' | 'behavioral' | 'final' | 'offer' | 'other'
          scheduled_at?: string | null
          status?: 'scheduled' | 'completed' | 'cancelled' | 'rescheduled'
          prep_notes?: string | null
          questions_asked?: string[] | null
          interviewer_names?: string[] | null
          feedback?: string | null
          follow_up_date?: string | null
          follow_up_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          company_id?: string | null
          company_name?: string
          position?: string
          interview_type?: 'phone_screen' | 'technical' | 'behavioral' | 'final' | 'offer' | 'other'
          scheduled_at?: string | null
          status?: 'scheduled' | 'completed' | 'cancelled' | 'rescheduled'
          prep_notes?: string | null
          questions_asked?: string[] | null
          interviewer_names?: string[] | null
          feedback?: string | null
          follow_up_date?: string | null
          follow_up_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      mentorship_sessions: {
        Row: {
          id: string
          plan_id: string | null
          host_id: string
          attendee_id: string
          title: string
          description: string | null
          session_type: 'one_time' | 'recurring'
          status: 'proposed' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          proposed_times: Json | null
          scheduled_start: string | null
          scheduled_end: string | null
          duration_minutes: number
          timezone: string
          recurrence_rule: 'weekly' | 'biweekly' | null
          recurrence_end_date: string | null
          parent_session_id: string | null
          meeting_provider: 'google_meet' | 'zoom' | 'manual' | null
          meeting_link: string | null
          meeting_id: string | null
          actual_duration_minutes: number | null
          session_notes: string | null
          outcomes: Json | null
          created_at: string
          updated_at: string
          confirmed_at: string | null
          completed_at: string | null
          cancelled_at: string | null
          cancellation_reason: string | null
        }
        Insert: {
          id?: string
          plan_id?: string | null
          host_id: string
          attendee_id: string
          title: string
          description?: string | null
          session_type?: 'one_time' | 'recurring'
          status?: 'proposed' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          proposed_times?: Json | null
          scheduled_start?: string | null
          scheduled_end?: string | null
          duration_minutes?: number
          timezone?: string
          recurrence_rule?: 'weekly' | 'biweekly' | null
          recurrence_end_date?: string | null
          parent_session_id?: string | null
          meeting_provider?: 'google_meet' | 'zoom' | 'manual' | null
          meeting_link?: string | null
          meeting_id?: string | null
          actual_duration_minutes?: number | null
          session_notes?: string | null
          outcomes?: Json | null
          created_at?: string
          updated_at?: string
          confirmed_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
          cancellation_reason?: string | null
        }
        Update: {
          id?: string
          plan_id?: string | null
          host_id?: string
          attendee_id?: string
          title?: string
          description?: string | null
          session_type?: 'one_time' | 'recurring'
          status?: 'proposed' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          proposed_times?: Json | null
          scheduled_start?: string | null
          scheduled_end?: string | null
          duration_minutes?: number
          timezone?: string
          recurrence_rule?: 'weekly' | 'biweekly' | null
          recurrence_end_date?: string | null
          parent_session_id?: string | null
          meeting_provider?: 'google_meet' | 'zoom' | 'manual' | null
          meeting_link?: string | null
          meeting_id?: string | null
          actual_duration_minutes?: number | null
          session_notes?: string | null
          outcomes?: Json | null
          created_at?: string
          updated_at?: string
          confirmed_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
          cancellation_reason?: string | null
        }
      }
      calendar_connections: {
        Row: {
          id: string
          user_id: string
          provider: 'google' | 'microsoft' | 'apple'
          access_token: string | null
          refresh_token: string | null
          token_expires_at: string | null
          calendar_id: string | null
          calendar_email: string | null
          is_active: boolean
          last_sync_at: string | null
          sync_error: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: 'google' | 'microsoft' | 'apple'
          access_token?: string | null
          refresh_token?: string | null
          token_expires_at?: string | null
          calendar_id?: string | null
          calendar_email?: string | null
          is_active?: boolean
          last_sync_at?: string | null
          sync_error?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: 'google' | 'microsoft' | 'apple'
          access_token?: string | null
          refresh_token?: string | null
          token_expires_at?: string | null
          calendar_id?: string | null
          calendar_email?: string | null
          is_active?: boolean
          last_sync_at?: string | null
          sync_error?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      session_reminders: {
        Row: {
          id: string
          session_id: string
          user_id: string
          reminder_type: '24_hours' | '1_hour' | 'custom'
          reminder_time: string
          email_sent: boolean
          email_sent_at: string | null
          in_app_sent: boolean
          in_app_sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          reminder_type: '24_hours' | '1_hour' | 'custom'
          reminder_time: string
          email_sent?: boolean
          email_sent_at?: string | null
          in_app_sent?: boolean
          in_app_sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          reminder_type?: '24_hours' | '1_hour' | 'custom'
          reminder_time?: string
          email_sent?: boolean
          email_sent_at?: string | null
          in_app_sent?: boolean
          in_app_sent_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
